In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df = pd.read_csv('/content/drive/MyDrive/Curso aprendizaje automatico/Semana 3/Clase 1/data_banknote_authentication.txt', sep=',', header=None)
df.head()

0       1       2        3  4
0  3.62160  8.6661 -2.8073 -0.44699  0
1  4.54590  8.1674 -2.4586 -1.46210  0
2  3.86600 -2.6383  1.9242  0.10645  0
3  3.45660  9.5228 -4.0112 -3.59440  0
4  0.32924 -4.4552  4.5718 -0.98880  0

In [4]:
X = df.iloc[:,0:4].values
y = df.iloc[:,4:].values

In [5]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [6]:
print(x_train.shape)
print(y_train.shape)

print(x_test.shape)
print(y_test.shape)

print(x_train[0:50,:])
print(y_train[0:50,:])

print(x_test[0:50,:])
print(y_test[0:50,:])

(960, 4)
(960, 1)
(412, 4)
(412, 1)
[[-2.74190e+00  1.14038e+01  2.53940e+00 -5.57930e+00]
 [ 3.62770e+00  9.82900e-01  6.88610e-01  6.34030e-01]
 [-2.58990e+00 -3.91100e-01  9.34520e-01  4.29720e-01]
 [ 3.98990e+00 -2.70660e+00  2.39460e+00  8.62910e-01]
 [ 2.26340e+00 -4.48620e+00  3.65580e+00 -6.12510e-01]
 [ 3.86440e+00  3.70610e+00  7.04030e-01  3.52140e-01]
 [-4.94470e+00  3.30050e+00  1.06300e+00 -1.44400e+00]
 [-6.20030e+00  8.68060e+00  9.13440e-03 -3.70300e+00]
 [-4.47790e+00  7.37080e+00 -3.12180e-01 -6.77540e+00]
 [-2.65900e+00 -1.60580e+00  1.36470e+00  1.64640e-01]
 [ 2.97190e+00  6.83690e+00 -2.70200e-01  7.12910e-01]
 [-2.16680e+00  1.59330e+00  4.51220e-02 -1.67800e+00]
 [-2.32990e+00 -9.95320e+00  8.47560e+00 -1.87330e+00]
 [ 1.23090e+00  3.89230e+00 -4.82770e+00 -4.00690e+00]
 [-9.54030e-01  1.98240e+00 -2.31630e+00 -1.19570e+00]
 [ 3.47690e+00 -1.53140e-01  2.53000e+00  2.44950e+00]
 [ 5.26200e+00  3.98340e+00 -1.55720e+00  1.01030e+00]
 [-6.98790e-01 -3.37710e+00  

In [7]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [8]:
all_predict = lr.predict(x_test)
print(all_predict)

print("Datos de Validacion\n", y_test)


[1 0 1 0 0 1 1 0 0 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 0 0 0 0 0 0 0 1 1 1
 0 0 1 0 1 0 0 1 1 1 0 0 1 1 1 0 1 1 0 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 1 1 0
 0 1 0 1 1 0 0 1 1 1 0 0 1 1 1 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1
 0 1 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 1 1 0 0 1 0 1 0 1 0
 0 1 0 0 1 0 0 1 1 1 0 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 0 0 1 1 1 1 0 1
 0 1 0 1 1 0 0 1 0 0 1 0 1 0 0 0 0 1 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0
 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 0 0 1 1 0 1 0 1 1 1 1 0 0 1 0
 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 1 0 0 1 0 1
 0 0 0 1 0 0 0 1 0 0 0 1 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0 0 0 1 1 0
 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0
 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 0 0 0 1 0 1 1 0 1
 0 0 1 1 0]
Datos de Validacion
 [[1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [